### ISSUE TITLE
what to call "footprints"

### ISSUE THREAD

**Issue by ericprud** [janeirodigital/shapetrees#7]
These footprints are different from TimBL and RubenV's footprints, as described below. Some proposals:

| template      | instance               | verb        | Docs with that terminology |
| ---           | ---                    | ---         | --- |
| shape tree    | shape tree instance    | plant       | [primer](https://janeirodigital.github.io/footprints/primer?shape%20tree,shape%20tree%20instance,plant) |
| footprint     | footprint instance     | stomp       | [primer](https://janeirodigital.github.io/footprints/primer?footprint,footprint%20instance,stomp) |
| blueprint     | imprint                | imprint     | [primer](https://janeirodigital.github.io/footprints/primer?blueprint,imprint,imprint) |
| constellation | constellation instance | instantiate | [primer](https://janeirodigital.github.io/footprints/primer?constellation,constellation%20instance,instantiate) |
| seed          | shrub                  | plant       | [primer](https://janeirodigital.github.io/footprints/primer?seed,shrub,plant) |

# these footprints -- constellations of resources
Fundamentally, these footprints are templates which have ldp:Container instances.
These follow the rules laid out by the footprint:
  1. assocation of resources to shapes (presumption that exactly one node conforms)
  2. nested resource naming conventions
Applications link to one or more footprints; this advertisement declares compatibility with that footprint. 
Where a user has installed only one instance, they direct applications to find exsiting data and store new data.
These Footprints don't try to construct semantic URLs.

``` turtle
<#container> foot:type ldp:BasicContainer ;
  foot:contents <#note> .

<#note> foot:name "Note" ;
  foot:type BasicContainer ;
  foot:shape <NeverNoteSchema#Note> ;
  foot:contents <#media> .

<#media> foot:name "Media" ;
  foot:type ldp:Resource .
```

produces Resources like `https://alice.pod/Data/Notes/Note1/Media2.jpg`

# TimBL/Ruben:Footprints -- constellations of shapes
Form elements link to footprints for:
  1. semantic URL construction from e.g. UUIDs, names, URLs
  2. (allusion to) how to construct link triples from form cells
  3. shape conformance
  4. mention of public, private, collaborative indexes

## example

``` turtle
<#note> a fp:Footprint;
  fp:arc <NeverNoteSchema#Note-tc-> ;
  fp:base fp:Source;                   # https://alice.pod/Data/Notes
  fp:uriTemplate "{noteName}/";
  fp:binding [
    fp:variable "noteName";            # variable binding structure
    fp:value [
      fp:SanitizeOf [                  # function
        fp:objectOfArc shape:Group_fn    # triple pattern
 ] ] ].

<#media> foot:name "Media" ;
  foot:type ldp:Resource .

:groupFootprint a fp:Footprint;
  fp:arc shape:AddressBook_includesGroup;
  fp:base fp:Source;                   # provides base for the relative URL below
  fp:uriTemplate "Group/{name}/index.ttl#this";
  fp:binding [
    fp:variable "name";                # variable binding structure
    fp:value [
      fp:SanitizeOf [                  # function
        fp:objectOfArc shape:Group_fn  # triple pattern
 ] ] ].
```

## Ruben's emphasis
Suggests ability to send notifications.

Aimed only at directing storage of new data rather than updates (via forms).

**Comment by justinwb** [comment]
I'm a 👍 for Shape Trees

**Comment by justinwb** [comment]
Accepted name is "Shape Trees", per the minutes from [2020-04-20 data interoperability panel meeting](https://github.com/solid/data-interoperability-panel/blob/master/meetings/12-20200420.md):

PROPOSED: rename footprints to Shape Trees
[offline support from TimBL, Ruben, Dimitri, Pat]
ericP: +1
justin: +1
elf: +1
jackson: +1
josh: +1
RESOLVED
